# Generated by Django 4.2 on 2023-04-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('website', models.URLField(unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
