# Generated by Django 4.2 on 2023-04-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passwords',
        ),
    ]
